/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.15.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QPushButton *BTN_START_CHARGING;
    QPushButton *BTN_STOP_CHARGING;
    QLabel *label;
    QLabel *label_2;
    QLineEdit *LE_STATE_STATION_IDLE;
    QLineEdit *LE_STATE_STATION_5V_ON;
    QLineEdit *LE_STATE_STATION_CHARGER_ON;
    QLineEdit *LE_STATE_STATION_CHARGING;
    QLineEdit *LE_STATE_STATION_CHARGER_OFF;
    QLineEdit *LE_STATE_STATION_FAIL;
    QLineEdit *LE_STATE_AMR_IDLE;
    QLineEdit *LE_STATE_AMR_TRIG_TO_CHARGE;
    QLineEdit *LE_STATE_AMR_BATTERY_ON;
    QLineEdit *LE_STATE_AMR_CHARGING;
    QLineEdit *LE_STATE_AMR_TRIG_TO_STOP;
    QLineEdit *LE_STATE_AMR_FAIL;
    QLineEdit *LE_STATION_LIMIT;
    QLabel *label_3;
    QLabel *label_4;
    QLineEdit *LE_STATION_CURRENT_1;
    QLineEdit *LE_STATION_CURRENT_2;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLineEdit *LE_STATION_VOLTAGE_2;
    QLineEdit *LE_STATION_VOLTAGE_1;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLineEdit *LE_AMR_CURRENT_1;
    QLabel *label_11;
    QLineEdit *LE_AMR_CURRENT_2;
    QLineEdit *LE_AMR_VOLTAGE_2;
    QLineEdit *LE_AMR_VOLTAGE_1;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QPushButton *BMS_LOG_AUTO;
    QLineEdit *BMS_VOLTAGE;
    QLineEdit *BMS_CURRENT;
    QLineEdit *CAN_STATE_IDLE;
    QLabel *label_15;
    QLabel *label_16;
    QPushButton *BMS_LOG_POLLING;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLineEdit *BMS_TTF;
    QLineEdit *BMS_TTE;
    QLineEdit *BMS_SOC;
    QLineEdit *BMS_SOH;
    QLabel *label_22;
    QLabel *label_23;
    QLineEdit *BMS_RC;
    QLineEdit *BMS_AE;
    QLineEdit *BMS_TEMP;
    QLabel *label_24;
    QPushButton *BMS_LOG_AUTO_STOP;
    QLineEdit *BMS_ERROR_OV;
    QLineEdit *BMS_ERROR_LV;
    QLineEdit *BMS_ERROR_OCC;
    QLineEdit *BMS_ERROR_LDC;
    QLineEdit *BMS_ERROR_OT;
    QLineEdit *BMS_ERROR_LT;
    QLineEdit *BMS_ERROR_BMS_ERROR;
    QLineEdit *SAVE_LOG;
    QLineEdit *input_string;
    QPushButton *SAVE_BUTTON;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(800, 832);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        BTN_START_CHARGING = new QPushButton(centralwidget);
        BTN_START_CHARGING->setObjectName(QString::fromUtf8("BTN_START_CHARGING"));
        BTN_START_CHARGING->setGeometry(QRect(20, 20, 131, 71));
        QFont font;
        font.setPointSize(6);
        BTN_START_CHARGING->setFont(font);
        BTN_STOP_CHARGING = new QPushButton(centralwidget);
        BTN_STOP_CHARGING->setObjectName(QString::fromUtf8("BTN_STOP_CHARGING"));
        BTN_STOP_CHARGING->setGeometry(QRect(210, 20, 131, 71));
        BTN_STOP_CHARGING->setFont(font);
        label = new QLabel(centralwidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(20, 140, 131, 41));
        label->setFont(font);
        label->setAlignment(Qt::AlignCenter);
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(350, 140, 131, 41));
        label_2->setFont(font);
        label_2->setAlignment(Qt::AlignCenter);
        LE_STATE_STATION_IDLE = new QLineEdit(centralwidget);
        LE_STATE_STATION_IDLE->setObjectName(QString::fromUtf8("LE_STATE_STATION_IDLE"));
        LE_STATE_STATION_IDLE->setGeometry(QRect(20, 190, 131, 25));
        LE_STATE_STATION_IDLE->setFont(font);
        LE_STATE_STATION_IDLE->setAlignment(Qt::AlignCenter);
        LE_STATE_STATION_IDLE->setReadOnly(true);
        LE_STATE_STATION_5V_ON = new QLineEdit(centralwidget);
        LE_STATE_STATION_5V_ON->setObjectName(QString::fromUtf8("LE_STATE_STATION_5V_ON"));
        LE_STATE_STATION_5V_ON->setGeometry(QRect(20, 220, 131, 25));
        LE_STATE_STATION_5V_ON->setFont(font);
        LE_STATE_STATION_5V_ON->setAlignment(Qt::AlignCenter);
        LE_STATE_STATION_5V_ON->setReadOnly(true);
        LE_STATE_STATION_CHARGER_ON = new QLineEdit(centralwidget);
        LE_STATE_STATION_CHARGER_ON->setObjectName(QString::fromUtf8("LE_STATE_STATION_CHARGER_ON"));
        LE_STATE_STATION_CHARGER_ON->setGeometry(QRect(20, 250, 131, 25));
        LE_STATE_STATION_CHARGER_ON->setFont(font);
        LE_STATE_STATION_CHARGER_ON->setAlignment(Qt::AlignCenter);
        LE_STATE_STATION_CHARGER_ON->setReadOnly(true);
        LE_STATE_STATION_CHARGING = new QLineEdit(centralwidget);
        LE_STATE_STATION_CHARGING->setObjectName(QString::fromUtf8("LE_STATE_STATION_CHARGING"));
        LE_STATE_STATION_CHARGING->setGeometry(QRect(20, 280, 131, 25));
        LE_STATE_STATION_CHARGING->setFont(font);
        LE_STATE_STATION_CHARGING->setAlignment(Qt::AlignCenter);
        LE_STATE_STATION_CHARGING->setReadOnly(true);
        LE_STATE_STATION_CHARGER_OFF = new QLineEdit(centralwidget);
        LE_STATE_STATION_CHARGER_OFF->setObjectName(QString::fromUtf8("LE_STATE_STATION_CHARGER_OFF"));
        LE_STATE_STATION_CHARGER_OFF->setGeometry(QRect(20, 310, 131, 25));
        LE_STATE_STATION_CHARGER_OFF->setFont(font);
        LE_STATE_STATION_CHARGER_OFF->setAlignment(Qt::AlignCenter);
        LE_STATE_STATION_CHARGER_OFF->setReadOnly(true);
        LE_STATE_STATION_FAIL = new QLineEdit(centralwidget);
        LE_STATE_STATION_FAIL->setObjectName(QString::fromUtf8("LE_STATE_STATION_FAIL"));
        LE_STATE_STATION_FAIL->setGeometry(QRect(20, 340, 131, 25));
        LE_STATE_STATION_FAIL->setFont(font);
        LE_STATE_STATION_FAIL->setAlignment(Qt::AlignCenter);
        LE_STATE_STATION_FAIL->setReadOnly(true);
        LE_STATE_AMR_IDLE = new QLineEdit(centralwidget);
        LE_STATE_AMR_IDLE->setObjectName(QString::fromUtf8("LE_STATE_AMR_IDLE"));
        LE_STATE_AMR_IDLE->setGeometry(QRect(350, 190, 131, 25));
        LE_STATE_AMR_IDLE->setFont(font);
        LE_STATE_AMR_IDLE->setAlignment(Qt::AlignCenter);
        LE_STATE_AMR_IDLE->setReadOnly(true);
        LE_STATE_AMR_TRIG_TO_CHARGE = new QLineEdit(centralwidget);
        LE_STATE_AMR_TRIG_TO_CHARGE->setObjectName(QString::fromUtf8("LE_STATE_AMR_TRIG_TO_CHARGE"));
        LE_STATE_AMR_TRIG_TO_CHARGE->setGeometry(QRect(350, 220, 131, 25));
        LE_STATE_AMR_TRIG_TO_CHARGE->setFont(font);
        LE_STATE_AMR_TRIG_TO_CHARGE->setAlignment(Qt::AlignCenter);
        LE_STATE_AMR_TRIG_TO_CHARGE->setReadOnly(true);
        LE_STATE_AMR_BATTERY_ON = new QLineEdit(centralwidget);
        LE_STATE_AMR_BATTERY_ON->setObjectName(QString::fromUtf8("LE_STATE_AMR_BATTERY_ON"));
        LE_STATE_AMR_BATTERY_ON->setGeometry(QRect(350, 250, 131, 25));
        LE_STATE_AMR_BATTERY_ON->setFont(font);
        LE_STATE_AMR_BATTERY_ON->setAlignment(Qt::AlignCenter);
        LE_STATE_AMR_BATTERY_ON->setReadOnly(true);
        LE_STATE_AMR_CHARGING = new QLineEdit(centralwidget);
        LE_STATE_AMR_CHARGING->setObjectName(QString::fromUtf8("LE_STATE_AMR_CHARGING"));
        LE_STATE_AMR_CHARGING->setGeometry(QRect(350, 280, 131, 25));
        LE_STATE_AMR_CHARGING->setFont(font);
        LE_STATE_AMR_CHARGING->setAlignment(Qt::AlignCenter);
        LE_STATE_AMR_CHARGING->setReadOnly(true);
        LE_STATE_AMR_TRIG_TO_STOP = new QLineEdit(centralwidget);
        LE_STATE_AMR_TRIG_TO_STOP->setObjectName(QString::fromUtf8("LE_STATE_AMR_TRIG_TO_STOP"));
        LE_STATE_AMR_TRIG_TO_STOP->setGeometry(QRect(350, 310, 131, 25));
        LE_STATE_AMR_TRIG_TO_STOP->setFont(font);
        LE_STATE_AMR_TRIG_TO_STOP->setAlignment(Qt::AlignCenter);
        LE_STATE_AMR_TRIG_TO_STOP->setReadOnly(true);
        LE_STATE_AMR_FAIL = new QLineEdit(centralwidget);
        LE_STATE_AMR_FAIL->setObjectName(QString::fromUtf8("LE_STATE_AMR_FAIL"));
        LE_STATE_AMR_FAIL->setGeometry(QRect(350, 340, 131, 25));
        LE_STATE_AMR_FAIL->setFont(font);
        LE_STATE_AMR_FAIL->setAlignment(Qt::AlignCenter);
        LE_STATE_AMR_FAIL->setReadOnly(true);
        LE_STATION_LIMIT = new QLineEdit(centralwidget);
        LE_STATION_LIMIT->setObjectName(QString::fromUtf8("LE_STATION_LIMIT"));
        LE_STATION_LIMIT->setGeometry(QRect(20, 400, 131, 51));
        LE_STATION_LIMIT->setFont(font);
        LE_STATION_LIMIT->setAlignment(Qt::AlignCenter);
        LE_STATION_LIMIT->setReadOnly(true);
        label_3 = new QLabel(centralwidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(170, 140, 131, 41));
        label_3->setFont(font);
        label_3->setAlignment(Qt::AlignCenter);
        label_4 = new QLabel(centralwidget);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(500, 140, 131, 41));
        label_4->setFont(font);
        label_4->setAlignment(Qt::AlignCenter);
        LE_STATION_CURRENT_1 = new QLineEdit(centralwidget);
        LE_STATION_CURRENT_1->setObjectName(QString::fromUtf8("LE_STATION_CURRENT_1"));
        LE_STATION_CURRENT_1->setGeometry(QRect(170, 220, 61, 25));
        LE_STATION_CURRENT_1->setFont(font);
        LE_STATION_CURRENT_1->setAlignment(Qt::AlignCenter);
        LE_STATION_CURRENT_1->setReadOnly(true);
        LE_STATION_CURRENT_2 = new QLineEdit(centralwidget);
        LE_STATION_CURRENT_2->setObjectName(QString::fromUtf8("LE_STATION_CURRENT_2"));
        LE_STATION_CURRENT_2->setGeometry(QRect(240, 220, 61, 25));
        LE_STATION_CURRENT_2->setFont(font);
        LE_STATION_CURRENT_2->setAlignment(Qt::AlignCenter);
        LE_STATION_CURRENT_2->setReadOnly(true);
        label_5 = new QLabel(centralwidget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(170, 200, 61, 17));
        label_5->setFont(font);
        label_5->setAlignment(Qt::AlignCenter);
        label_6 = new QLabel(centralwidget);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(240, 200, 61, 17));
        label_6->setFont(font);
        label_6->setAlignment(Qt::AlignCenter);
        label_7 = new QLabel(centralwidget);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(170, 270, 131, 41));
        label_7->setFont(font);
        label_7->setAlignment(Qt::AlignCenter);
        LE_STATION_VOLTAGE_2 = new QLineEdit(centralwidget);
        LE_STATION_VOLTAGE_2->setObjectName(QString::fromUtf8("LE_STATION_VOLTAGE_2"));
        LE_STATION_VOLTAGE_2->setGeometry(QRect(240, 340, 61, 25));
        LE_STATION_VOLTAGE_2->setFont(font);
        LE_STATION_VOLTAGE_2->setAlignment(Qt::AlignCenter);
        LE_STATION_VOLTAGE_2->setReadOnly(true);
        LE_STATION_VOLTAGE_1 = new QLineEdit(centralwidget);
        LE_STATION_VOLTAGE_1->setObjectName(QString::fromUtf8("LE_STATION_VOLTAGE_1"));
        LE_STATION_VOLTAGE_1->setGeometry(QRect(170, 340, 61, 25));
        LE_STATION_VOLTAGE_1->setFont(font);
        LE_STATION_VOLTAGE_1->setAlignment(Qt::AlignCenter);
        LE_STATION_VOLTAGE_1->setReadOnly(true);
        label_8 = new QLabel(centralwidget);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(240, 320, 61, 17));
        label_8->setFont(font);
        label_8->setAlignment(Qt::AlignCenter);
        label_9 = new QLabel(centralwidget);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(170, 320, 61, 17));
        label_9->setFont(font);
        label_9->setAlignment(Qt::AlignCenter);
        label_10 = new QLabel(centralwidget);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(500, 190, 61, 17));
        label_10->setFont(font);
        label_10->setAlignment(Qt::AlignCenter);
        LE_AMR_CURRENT_1 = new QLineEdit(centralwidget);
        LE_AMR_CURRENT_1->setObjectName(QString::fromUtf8("LE_AMR_CURRENT_1"));
        LE_AMR_CURRENT_1->setGeometry(QRect(500, 210, 61, 25));
        LE_AMR_CURRENT_1->setFont(font);
        LE_AMR_CURRENT_1->setAlignment(Qt::AlignCenter);
        LE_AMR_CURRENT_1->setReadOnly(true);
        label_11 = new QLabel(centralwidget);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(570, 190, 61, 17));
        label_11->setFont(font);
        label_11->setAlignment(Qt::AlignCenter);
        LE_AMR_CURRENT_2 = new QLineEdit(centralwidget);
        LE_AMR_CURRENT_2->setObjectName(QString::fromUtf8("LE_AMR_CURRENT_2"));
        LE_AMR_CURRENT_2->setGeometry(QRect(570, 210, 61, 25));
        LE_AMR_CURRENT_2->setFont(font);
        LE_AMR_CURRENT_2->setAlignment(Qt::AlignCenter);
        LE_AMR_CURRENT_2->setReadOnly(true);
        LE_AMR_VOLTAGE_2 = new QLineEdit(centralwidget);
        LE_AMR_VOLTAGE_2->setObjectName(QString::fromUtf8("LE_AMR_VOLTAGE_2"));
        LE_AMR_VOLTAGE_2->setGeometry(QRect(570, 340, 61, 25));
        LE_AMR_VOLTAGE_2->setFont(font);
        LE_AMR_VOLTAGE_2->setAlignment(Qt::AlignCenter);
        LE_AMR_VOLTAGE_2->setReadOnly(true);
        LE_AMR_VOLTAGE_1 = new QLineEdit(centralwidget);
        LE_AMR_VOLTAGE_1->setObjectName(QString::fromUtf8("LE_AMR_VOLTAGE_1"));
        LE_AMR_VOLTAGE_1->setGeometry(QRect(500, 340, 61, 25));
        LE_AMR_VOLTAGE_1->setFont(font);
        LE_AMR_VOLTAGE_1->setAlignment(Qt::AlignCenter);
        LE_AMR_VOLTAGE_1->setReadOnly(true);
        label_12 = new QLabel(centralwidget);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(500, 270, 131, 41));
        label_12->setFont(font);
        label_12->setAlignment(Qt::AlignCenter);
        label_13 = new QLabel(centralwidget);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(500, 320, 61, 17));
        label_13->setFont(font);
        label_13->setAlignment(Qt::AlignCenter);
        label_14 = new QLabel(centralwidget);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(570, 320, 61, 17));
        label_14->setFont(font);
        label_14->setAlignment(Qt::AlignCenter);
        BMS_LOG_AUTO = new QPushButton(centralwidget);
        BMS_LOG_AUTO->setObjectName(QString::fromUtf8("BMS_LOG_AUTO"));
        BMS_LOG_AUTO->setGeometry(QRect(20, 520, 131, 61));
        QFont font1;
        font1.setPointSize(5);
        BMS_LOG_AUTO->setFont(font1);
        BMS_VOLTAGE = new QLineEdit(centralwidget);
        BMS_VOLTAGE->setObjectName(QString::fromUtf8("BMS_VOLTAGE"));
        BMS_VOLTAGE->setGeometry(QRect(170, 520, 61, 25));
        BMS_VOLTAGE->setFont(font1);
        BMS_VOLTAGE->setContextMenuPolicy(Qt::DefaultContextMenu);
        BMS_VOLTAGE->setAlignment(Qt::AlignCenter);
        BMS_VOLTAGE->setReadOnly(true);
        BMS_CURRENT = new QLineEdit(centralwidget);
        BMS_CURRENT->setObjectName(QString::fromUtf8("BMS_CURRENT"));
        BMS_CURRENT->setGeometry(QRect(250, 520, 61, 25));
        BMS_CURRENT->setFont(font1);
        BMS_CURRENT->setContextMenuPolicy(Qt::DefaultContextMenu);
        BMS_CURRENT->setAlignment(Qt::AlignCenter);
        BMS_CURRENT->setReadOnly(true);
        CAN_STATE_IDLE = new QLineEdit(centralwidget);
        CAN_STATE_IDLE->setObjectName(QString::fromUtf8("CAN_STATE_IDLE"));
        CAN_STATE_IDLE->setGeometry(QRect(20, 490, 131, 25));
        CAN_STATE_IDLE->setFont(font1);
        CAN_STATE_IDLE->setAlignment(Qt::AlignCenter);
        CAN_STATE_IDLE->setReadOnly(true);
        label_15 = new QLabel(centralwidget);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(150, 490, 91, 17));
        label_15->setFont(font1);
        label_15->setAlignment(Qt::AlignCenter);
        label_16 = new QLabel(centralwidget);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(230, 490, 91, 17));
        label_16->setFont(font1);
        label_16->setAlignment(Qt::AlignCenter);
        BMS_LOG_POLLING = new QPushButton(centralwidget);
        BMS_LOG_POLLING->setObjectName(QString::fromUtf8("BMS_LOG_POLLING"));
        BMS_LOG_POLLING->setGeometry(QRect(20, 590, 131, 61));
        BMS_LOG_POLLING->setFont(font1);
        label_17 = new QLabel(centralwidget);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(660, 430, 91, 17));
        label_17->setFont(font1);
        label_17->setAlignment(Qt::AlignCenter);
        label_18 = new QLabel(centralwidget);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(150, 560, 91, 17));
        label_18->setFont(font1);
        label_18->setAlignment(Qt::AlignCenter);
        label_19 = new QLabel(centralwidget);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(230, 560, 91, 17));
        label_19->setFont(font1);
        label_19->setAlignment(Qt::AlignCenter);
        label_20 = new QLabel(centralwidget);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(310, 560, 91, 17));
        label_20->setFont(font1);
        label_20->setAlignment(Qt::AlignCenter);
        label_21 = new QLabel(centralwidget);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(400, 560, 91, 17));
        label_21->setFont(font1);
        label_21->setAlignment(Qt::AlignCenter);
        BMS_TTF = new QLineEdit(centralwidget);
        BMS_TTF->setObjectName(QString::fromUtf8("BMS_TTF"));
        BMS_TTF->setGeometry(QRect(170, 580, 61, 25));
        BMS_TTF->setFont(font1);
        BMS_TTF->setContextMenuPolicy(Qt::DefaultContextMenu);
        BMS_TTF->setAlignment(Qt::AlignCenter);
        BMS_TTF->setReadOnly(true);
        BMS_TTE = new QLineEdit(centralwidget);
        BMS_TTE->setObjectName(QString::fromUtf8("BMS_TTE"));
        BMS_TTE->setGeometry(QRect(250, 580, 61, 25));
        BMS_TTE->setFont(font1);
        BMS_TTE->setContextMenuPolicy(Qt::DefaultContextMenu);
        BMS_TTE->setAlignment(Qt::AlignCenter);
        BMS_TTE->setReadOnly(true);
        BMS_SOC = new QLineEdit(centralwidget);
        BMS_SOC->setObjectName(QString::fromUtf8("BMS_SOC"));
        BMS_SOC->setGeometry(QRect(330, 580, 61, 25));
        BMS_SOC->setFont(font1);
        BMS_SOC->setContextMenuPolicy(Qt::DefaultContextMenu);
        BMS_SOC->setAlignment(Qt::AlignCenter);
        BMS_SOC->setReadOnly(true);
        BMS_SOH = new QLineEdit(centralwidget);
        BMS_SOH->setObjectName(QString::fromUtf8("BMS_SOH"));
        BMS_SOH->setGeometry(QRect(410, 580, 61, 25));
        BMS_SOH->setFont(font1);
        BMS_SOH->setContextMenuPolicy(Qt::DefaultContextMenu);
        BMS_SOH->setAlignment(Qt::AlignCenter);
        BMS_SOH->setReadOnly(true);
        label_22 = new QLabel(centralwidget);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(210, 616, 141, 21));
        label_22->setFont(font1);
        label_22->setAlignment(Qt::AlignCenter);
        label_23 = new QLabel(centralwidget);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(350, 616, 201, 21));
        label_23->setFont(font1);
        label_23->setAlignment(Qt::AlignCenter);
        BMS_RC = new QLineEdit(centralwidget);
        BMS_RC->setObjectName(QString::fromUtf8("BMS_RC"));
        BMS_RC->setGeometry(QRect(230, 640, 101, 25));
        BMS_RC->setFont(font1);
        BMS_RC->setContextMenuPolicy(Qt::DefaultContextMenu);
        BMS_RC->setAlignment(Qt::AlignCenter);
        BMS_RC->setReadOnly(true);
        BMS_AE = new QLineEdit(centralwidget);
        BMS_AE->setObjectName(QString::fromUtf8("BMS_AE"));
        BMS_AE->setGeometry(QRect(380, 640, 101, 25));
        BMS_AE->setFont(font1);
        BMS_AE->setContextMenuPolicy(Qt::DefaultContextMenu);
        BMS_AE->setAlignment(Qt::AlignCenter);
        BMS_AE->setReadOnly(true);
        BMS_TEMP = new QLineEdit(centralwidget);
        BMS_TEMP->setObjectName(QString::fromUtf8("BMS_TEMP"));
        BMS_TEMP->setGeometry(QRect(490, 580, 61, 25));
        BMS_TEMP->setFont(font1);
        BMS_TEMP->setContextMenuPolicy(Qt::DefaultContextMenu);
        BMS_TEMP->setAlignment(Qt::AlignCenter);
        BMS_TEMP->setReadOnly(true);
        label_24 = new QLabel(centralwidget);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(480, 560, 91, 17));
        label_24->setFont(font1);
        label_24->setAlignment(Qt::AlignCenter);
        BMS_LOG_AUTO_STOP = new QPushButton(centralwidget);
        BMS_LOG_AUTO_STOP->setObjectName(QString::fromUtf8("BMS_LOG_AUTO_STOP"));
        BMS_LOG_AUTO_STOP->setGeometry(QRect(20, 660, 131, 61));
        BMS_LOG_AUTO_STOP->setFont(font1);
        BMS_ERROR_OV = new QLineEdit(centralwidget);
        BMS_ERROR_OV->setObjectName(QString::fromUtf8("BMS_ERROR_OV"));
        BMS_ERROR_OV->setGeometry(QRect(650, 460, 131, 25));
        BMS_ERROR_OV->setFont(font);
        BMS_ERROR_OV->setAlignment(Qt::AlignCenter);
        BMS_ERROR_OV->setReadOnly(true);
        BMS_ERROR_LV = new QLineEdit(centralwidget);
        BMS_ERROR_LV->setObjectName(QString::fromUtf8("BMS_ERROR_LV"));
        BMS_ERROR_LV->setGeometry(QRect(650, 490, 131, 21));
        BMS_ERROR_LV->setFont(font);
        BMS_ERROR_LV->setAlignment(Qt::AlignCenter);
        BMS_ERROR_LV->setReadOnly(true);
        BMS_ERROR_OCC = new QLineEdit(centralwidget);
        BMS_ERROR_OCC->setObjectName(QString::fromUtf8("BMS_ERROR_OCC"));
        BMS_ERROR_OCC->setGeometry(QRect(650, 520, 131, 21));
        BMS_ERROR_OCC->setFont(font);
        BMS_ERROR_OCC->setAlignment(Qt::AlignCenter);
        BMS_ERROR_OCC->setReadOnly(true);
        BMS_ERROR_LDC = new QLineEdit(centralwidget);
        BMS_ERROR_LDC->setObjectName(QString::fromUtf8("BMS_ERROR_LDC"));
        BMS_ERROR_LDC->setGeometry(QRect(650, 550, 131, 21));
        BMS_ERROR_LDC->setFont(font);
        BMS_ERROR_LDC->setAlignment(Qt::AlignCenter);
        BMS_ERROR_LDC->setReadOnly(true);
        BMS_ERROR_OT = new QLineEdit(centralwidget);
        BMS_ERROR_OT->setObjectName(QString::fromUtf8("BMS_ERROR_OT"));
        BMS_ERROR_OT->setGeometry(QRect(650, 580, 131, 21));
        BMS_ERROR_OT->setFont(font);
        BMS_ERROR_OT->setAlignment(Qt::AlignCenter);
        BMS_ERROR_OT->setReadOnly(true);
        BMS_ERROR_LT = new QLineEdit(centralwidget);
        BMS_ERROR_LT->setObjectName(QString::fromUtf8("BMS_ERROR_LT"));
        BMS_ERROR_LT->setGeometry(QRect(650, 610, 131, 21));
        BMS_ERROR_LT->setFont(font);
        BMS_ERROR_LT->setAlignment(Qt::AlignCenter);
        BMS_ERROR_LT->setReadOnly(true);
        BMS_ERROR_BMS_ERROR = new QLineEdit(centralwidget);
        BMS_ERROR_BMS_ERROR->setObjectName(QString::fromUtf8("BMS_ERROR_BMS_ERROR"));
        BMS_ERROR_BMS_ERROR->setGeometry(QRect(650, 640, 131, 21));
        BMS_ERROR_BMS_ERROR->setFont(font);
        BMS_ERROR_BMS_ERROR->setAlignment(Qt::AlignCenter);
        BMS_ERROR_BMS_ERROR->setReadOnly(true);
        SAVE_LOG = new QLineEdit(centralwidget);
        SAVE_LOG->setObjectName(QString::fromUtf8("SAVE_LOG"));
        SAVE_LOG->setGeometry(QRect(650, 680, 61, 25));
        SAVE_LOG->setFont(font1);
        SAVE_LOG->setContextMenuPolicy(Qt::DefaultContextMenu);
        SAVE_LOG->setAlignment(Qt::AlignCenter);
        SAVE_LOG->setReadOnly(true);
        input_string = new QLineEdit(centralwidget);
        input_string->setObjectName(QString::fromUtf8("input_string"));
        input_string->setGeometry(QRect(500, 710, 113, 25));
        SAVE_BUTTON = new QPushButton(centralwidget);
        SAVE_BUTTON->setObjectName(QString::fromUtf8("SAVE_BUTTON"));
        SAVE_BUTTON->setGeometry(QRect(640, 720, 111, 31));
        SAVE_BUTTON->setFont(font);
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 800, 39));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        BTN_START_CHARGING->setText(QCoreApplication::translate("MainWindow", "Start Charging", nullptr));
        BTN_STOP_CHARGING->setText(QCoreApplication::translate("MainWindow", "Stop Charging", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "State [Station]", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "State [AMR]", nullptr));
        LE_STATE_STATION_IDLE->setText(QCoreApplication::translate("MainWindow", "IDLE", nullptr));
        LE_STATE_STATION_5V_ON->setText(QCoreApplication::translate("MainWindow", "5V ON", nullptr));
        LE_STATE_STATION_CHARGER_ON->setText(QCoreApplication::translate("MainWindow", "CHARGER ON", nullptr));
        LE_STATE_STATION_CHARGING->setText(QCoreApplication::translate("MainWindow", "CHARGING", nullptr));
        LE_STATE_STATION_CHARGER_OFF->setText(QCoreApplication::translate("MainWindow", "CHARGER OFF", nullptr));
        LE_STATE_STATION_FAIL->setText(QCoreApplication::translate("MainWindow", "FAIL", nullptr));
        LE_STATE_AMR_IDLE->setText(QCoreApplication::translate("MainWindow", "IDLE", nullptr));
        LE_STATE_AMR_TRIG_TO_CHARGE->setText(QCoreApplication::translate("MainWindow", "TRIG TO CHARGE", nullptr));
        LE_STATE_AMR_BATTERY_ON->setText(QCoreApplication::translate("MainWindow", "BATTERY ON", nullptr));
        LE_STATE_AMR_CHARGING->setText(QCoreApplication::translate("MainWindow", "CHARGING", nullptr));
        LE_STATE_AMR_TRIG_TO_STOP->setText(QCoreApplication::translate("MainWindow", "TRIG TO STOP", nullptr));
        LE_STATE_AMR_FAIL->setText(QCoreApplication::translate("MainWindow", "FAIL", nullptr));
        LE_STATION_LIMIT->setText(QCoreApplication::translate("MainWindow", "LIMIT", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "Current [Station]", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "Current [AMR]", nullptr));
        LE_STATION_CURRENT_1->setText(QString());
        LE_STATION_CURRENT_2->setText(QString());
        label_5->setText(QCoreApplication::translate("MainWindow", "charger", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "contact", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "Voltage [Station]", nullptr));
        LE_STATION_VOLTAGE_2->setText(QString());
        LE_STATION_VOLTAGE_1->setText(QString());
        label_8->setText(QCoreApplication::translate("MainWindow", "contact", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "charger", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "contact", nullptr));
        LE_AMR_CURRENT_1->setText(QString());
        label_11->setText(QCoreApplication::translate("MainWindow", "battery", nullptr));
        LE_AMR_CURRENT_2->setText(QString());
        LE_AMR_VOLTAGE_2->setText(QString());
        LE_AMR_VOLTAGE_1->setText(QString());
        label_12->setText(QCoreApplication::translate("MainWindow", "Voltage [AMR]", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "contact", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "battery", nullptr));
        BMS_LOG_AUTO->setText(QCoreApplication::translate("MainWindow", "BMS_LOG_AUTO", nullptr));
        BMS_VOLTAGE->setText(QString());
        BMS_CURRENT->setText(QString());
        CAN_STATE_IDLE->setText(QCoreApplication::translate("MainWindow", "CAN_STATE", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "voltage (v)", nullptr));
        label_16->setText(QCoreApplication::translate("MainWindow", "current (A)", nullptr));
        BMS_LOG_POLLING->setText(QCoreApplication::translate("MainWindow", "BMS_LOG_POLLING", nullptr));
        label_17->setText(QCoreApplication::translate("MainWindow", "status", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindow", "ttf (min)", nullptr));
        label_19->setText(QCoreApplication::translate("MainWindow", "tte (min)", nullptr));
        label_20->setText(QCoreApplication::translate("MainWindow", "soc(%)", nullptr));
        label_21->setText(QCoreApplication::translate("MainWindow", "soh (%)", nullptr));
        BMS_TTF->setText(QString());
        BMS_TTE->setText(QString());
        BMS_SOC->setText(QString());
        BMS_SOH->setText(QString());
        label_22->setText(QCoreApplication::translate("MainWindow", "remain capacity (Ah)", nullptr));
        label_23->setText(QCoreApplication::translate("MainWindow", "Available Energy (wh)", nullptr));
        BMS_RC->setText(QString());
        BMS_AE->setText(QString());
        BMS_TEMP->setText(QString());
        label_24->setText(QCoreApplication::translate("MainWindow", "temp (/c)", nullptr));
        BMS_LOG_AUTO_STOP->setText(QCoreApplication::translate("MainWindow", "BMS_LOG_STOP", nullptr));
        BMS_ERROR_OV->setText(QCoreApplication::translate("MainWindow", "\353\260\260\355\204\260\353\246\254 \352\263\274\354\240\204\354\225\225", nullptr));
        BMS_ERROR_LV->setText(QCoreApplication::translate("MainWindow", "\353\260\260\355\204\260\353\246\254 \354\240\200\354\240\204\354\225\225", nullptr));
        BMS_ERROR_OCC->setText(QCoreApplication::translate("MainWindow", "\354\266\251\354\240\204\354\240\204\353\245\230 \352\263\274\353\213\244", nullptr));
        BMS_ERROR_LDC->setText(QCoreApplication::translate("MainWindow", "\353\260\251\354\240\204\354\240\204\353\245\230 \352\263\274\353\213\244", nullptr));
        BMS_ERROR_OT->setText(QCoreApplication::translate("MainWindow", "\353\260\260\355\204\260\353\246\254 \352\263\240\354\230\250\353\217\204", nullptr));
        BMS_ERROR_LT->setText(QCoreApplication::translate("MainWindow", "\353\260\260\355\204\260\353\246\254 \354\240\200\354\230\250\353\217\204", nullptr));
        BMS_ERROR_BMS_ERROR->setText(QCoreApplication::translate("MainWindow", "BMS \354\227\220\353\237\254", nullptr));
        SAVE_LOG->setText(QString());
        SAVE_BUTTON->setText(QCoreApplication::translate("MainWindow", "save_button", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
